[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
NODE_ENV = "production"
API_PREFIX = "/api"
API_VERSION = "v1"
TRUST_PROXY = "true"
COMPRESSION_THRESHOLD = "1024"
HELMET_CONTENT_SECURITY_POLICY = "true"
RATE_LIMIT_WINDOW_MS = "900000"
RATE_LIMIT_MAX_REQUESTS = "100"
DEBUG_MODE = "false"
PRETTY_PRINT_JSON = "false"
DETAILED_ERRORS = "false"
HEALTH_CHECK_INTERVAL = "30000"
METRICS_ENABLED = "true"
SWAGGER_ENABLED = "false"
LOG_LEVEL = "combined"

# These will be set via Railway dashboard or CLI
# PORT is automatically set by Railway
# MONGODB_URI should be set as environment variable
# JWT_SECRET should be set as environment variable
# SESSION_SECRET should be set as environment variable
# FRONTEND_URL should be set as environment variable
